---
- hosts: controller
  connection: local

  vars_files:
    # - "vars/creds.yml"
    - "vars/params.yml"
    - "/home/avi/creds/avicontroller.azure.perso.yml"


  roles:
    - role: "avinetworks.avisdk"

  tasks:


  # - debug: var=inventory_file


  - name: generate vars/creds.yml
    command: "python3 generateJson.py {{ inventory_file }} {{ avi.controller.newPassword }} {{ avi.controller.version }}"
    delegate_to: 127.0.0.1
    register: generateJson

  - set_fact:
      avicreds: "{{ generateJson.stdout | from_json }}"

  - debug: var=avicreds


- hosts: localhost
  connection: local

  vars_files:
    # - "vars/creds.yml"
    - "vars/params.yml"
    - "/home/avi/creds/avicontroller.azure.perso.yml"


  roles:
    - role: "avinetworks.avisdk"


  tasks:

  - debug: var=generateJson
